choose_type: max_min
train_dir: ./data/data_with_rewards.jsonl
eval_dir: ./data/data_with_rewards.jsonl
run_name: LLaMA3_iter3
output_dir: LLaMA3_iter3
model_name_or_path: RLHFlow/LLaMA3.2-1B-SFT
ref_model: RLHFlow/LLaMA3.2-1B-SFT
pi_t_model: RLHFlow/LLaMA3.2-1B-SFT
bf16: true
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
gradient_accumulation_steps: 16
label_smoothing: 0.1
report_to: wandb
eval_steps: 10000
num_train_epochs: 2
logging_steps: 2
gradient_checkpointing: true
do_train: true
do_eval: true
loss_type: inpo
lr_scheduler_type: cosine
eval_strategy: steps
max_length: 2048
max_prompt_length: 1024
learning_rate: 5.0e-7